linaro-swg/optee_examples

Makefile

Seems, that something went wrong when addressing last comments in the previous PR, and `optee_` prefix was unintentionally deleted
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

make: fix CAs copy issue

---

aes/ta/aes_ta.c

This fixes issues seen on Travis during the weekend:
https://travis-ci.org/OP-TEE/build/jobs/301148288#L4676-L4705

AES TA: Fix compiler errors on AArch64

---

hotp/ta/hotp_ta.c

Got compiler error on size_t when running the AArch64 GCC. Changed it to use the same type as defined in the GP Internal Core API.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7, FVP)

hotp: change outlen to uint32_t in hmac_sha1

---

random/host/main.c

Fixes the following error:
main.c:95:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
for (int i = 0; i < 16; i++)
^
main.c:95:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

optee_random: fix compilation error with GCC 4.9

---

Makefile

This change decouples the actual examples from the optee_examples folder.  I have added `EXCLUDE_DIRS` to exclude special folders like `out` and `docs`.

Add command to determine EXAMPLE_LIST

---

CMakeLists.txt
CMakeToolchain.txt
aes/CMakeLists.txt
hello_world/CMakeLists.txt
hotp/CMakeLists.txt
random/CMakeLists.txt

This introduces support for building the host part (what's running in
linux user space) of optee_examples using CMake. TAs are as before built
using TA dev kit.
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

cmake support for host applications only (not TAs)

---

LICENSE
aes/host/Makefile
hello_world/host/Makefile
hotp/host/Makefile
random/host/Makefile

This pull request makes two changes to enable a bitbake recipe to build this repo in bitbake/yocto
1. Add a LICENSE file - bitbake requires a license
2. Allow the bitbake environment to specify CC, READELF and friends directly
Once done a minor modification to the xtest bitbake recipe can then build this repo, install to target and binaries run/pass.

Bitbake enabling pr

---

aes/Makefile
aes/host/Makefile
hello_world/Makefile
hello_world/host/Makefile
hotp/Makefile
hotp/host/Makefile
random/Makefile
random/host/Makefile

Commit 1d7d9ad85650 ("host/Makefiles: Allow CC variable to be derived
from env") changed the client application Makfiles so that $(CC) will
not be modified if already set. The intent was to take into account
the values derived from the environment or the command line.
Unfortunately, the "?=" syntax will also consider 'default' (built-in)
variables as shown in this example:
$ cat Makefile
$(info CC=$(CC) origin: $(origin CC))
CC ?= foo
$(info CC=$(CC) origin: $(origin CC))
all:
$ make
CC=cc origin: default
CC=cc origin: default
make: Nothing to be done for 'all'.
As a result, unless CC is specified via the environment or the command
line, its value defaults to 'cc' which is not what we want for cross
compilation.
This commit fixes the issue in a similar way to optee_test, by
disabling …

Use "make --no-builtin-variables" to build client applications

---

aes/Makefile
hello_world/Makefile
hotp/Makefile
random/Makefile

Yocto can set LDFLAGS to values that are incompatible with building a TA.
This patch ensures the LDFLAGS from the environment is unset prior to
importing make script settings, thus allowing us to compile up the TAs the
way we need to, while still accepting the LDFLAGS from yocto for the
host-side binaries.
This fix is exactly what we do in optee-test for this same issue.
Signed-off-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>

ta/Makefiles: Set LDFLAGS to null before importing ta make scripts

---

.gitignore
README.md
secure_storage/Android.mk
secure_storage/Makefile
secure_storage/host/Makefile
secure_storage/host/main.c
secure_storage/ta/Android.mk
secure_storage/ta/Makefile
secure_storage/ta/include/secure_storage_ta.h
secure_storage/ta/secure_storage_ta.c
secure_storage/ta/sub.mk
secure_storage/ta/user_ta_header_defines.h

secure_storage example provides basics for creating, reading and deleting
a object in a TA secure storage.
A TA command allows to create an object in the TA secure storage.
A TA command allows to read an object in the TA secure storage.
A TA command allows to delete an object from the TA secur storage.
This example does not cover all the possibilities of secure storage API
provided to TAs: seeking into a object data stream, manipulating
key material objects instead of raw data objects, etc.

raw secure storage accesses

---

hotp/host/main.c

optee_examples/hotp/host/main.c:92:16: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
for (i = 0; i < sizeof(rfc4226_test_values) / sizeof(struct test_value);
~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Victor Chong <victor.chong@linaro.org>

hotp: fix sign compare error

---

secure_storage/CMakeLists.txt

This will make the host binary end up in the Buildroot filesystem.

secure_storage: Add CMakeLists.txt

---

hello_world/ta/user_ta_header_defines.h
hotp/ta/user_ta_header_defines.h
random/ta/user_ta_header_defines.h

```
Some of our example TAs define the following properties:
- "gp.ta.description" (type: string)
- "gp.ta.version" (type: unsigned 32-bit integer)
This is misleading, because these are *not* the standard description and
version properties defined by the GP Internal Core API specification. The
standard ones are:
- "gpd.ta.description" (type: string)
- "gpd.ta.version" (type: string)
OP-TEE TAs should use the TA_DESCRIPTION and TA_VERSION macros to define
them.
This commit gets rid of the misleading properties. Instead, TA_DESCRIPTION
and TA_VERSION are set in the hello_world application. To still illustrate
the mechanism used to define non-standard properties, we add a couple of
values with names that follow the recommended reverse domain name
convention. Other TAs are left with no …
```

Remove misleading TA properties

---

aes/host/main.c

The initial vector in AES CRT mode is the first data block and
therefore has the size of block size as opposed ot the size of
the key. While Rijndael does support different block sizes AES
only supports 128 bits (16 bytes) block. Even with larger keys
sizes ( e.g. 192 or 256 bits) the block size remains 128 bits.
This change introduced a new constant AES_BLOCK_SIZE  and uses
this for IV related operations.

IV In AES CRT mode is always 128 bits regarldless the key size

---

acipher/CMakeLists.txt
aes/CMakeLists.txt
hello_world/CMakeLists.txt
hotp/CMakeLists.txt
random/CMakeLists.txt
secure_storage/CMakeLists.txt

Sync the CMake build with the GNU make and the Android make
process. All client applications generated by this package
are prefixed with optee_example_.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

cmake: prefix host tools file names with optee_example_

---

acipher/host/main.c

Fix build warning reported by GCC-8.2 as:
/path/to/optee_examples/acipher/host/main.c: In function ‘main’:
/path/to/optee_examples/acipher/host/main.c:108:7: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ [-Wformat=]
op.params[1].tmpref.size);
^
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

acipher: fix type in error trace

---

secure_storage/Android.mk
secure_storage/host/main.c

Resolves this:
```make
external/optee_examples/secure_storage/Android.mk: error: optee_example_secure_storage (native:platform) should not link to libteec (native:vendor)
[ 15% 2/13] target  C: optee_example_secure_storage <= external/optee_examples/secure_storage/host/main.c                      
FAILED: out/target/product/hikey/obj/EXECUTABLES/optee_example_secure_storage_intermediates/host/main.o                                               
/bin/bash -c "PWD=/proc/self/cwd prebuilts/misc/linux-x86/ccache/ccache prebuilts/clang/host/linux-x86/clang-4691093/bin/clang       -I external/optee_examples/secur
e_storage/ta/include -I external/optee_examples/secure_storage/../../optee_client/out/export/include -I external/optee_examples/secure_storage -I out/target/product/ …
```

Aosp ss fixes

---

secure_storage/ta/secure_storage_ta.c

PRI macro requires inttypes.h header
Signed-off-by: Ruslan Piasetskyi <ruslan.piasetskyi@gmail.com>
```
CC      /optee/obj/TA_OBJ/f4e750bb-1437-4fbf-8785-8d3580c34994_OBJ/secure_storage_ta.o
In file included from /optee/obj/OPTEE_OBJ/export-ta_arm64/include/tee_api.h:38:0,
from /optee/obj/OPTEE_OBJ/export-ta_arm64/include/tee_internal_api.h:33,
from secure_storage_ta.c:29:
secure_storage_ta.c: In function ‘read_raw_object’:
secure_storage_ta.c:205:51: error: expected ‘)’ before ‘PRIu32’
EMSG("TEE_ReadObjectData failed 0x%08x, read %" PRIu32 " over %u",
^
/optee/obj/OPTEE_OBJ/export-ta_arm64/include/trace.h:59:8: note: in definition of macro ‘trace_printf_helper’
__VA_ARGS__)
^~~~~~~~~~~
secure_storage_ta.c:205:3: note: in expansion of macro ‘EMSG’
EMSG("TEE_ReadObjectData failed 0x%08x, …
```

sstorage: Add missed header

---

acipher/host/main.c

LONG_MAX is defined in limits.h header
optee_examples/acipher/host/main.c:46:22: error:
use of undeclared identifier 'LONG_MAX'

acipher: add missed header

---

acipher/ta/user_ta_header_defines.h

With optee_os 3.0.0 and below, optee_example_acipher is failed with
the following error:
optee_example_acipher: TEEC_OpenSession(TEEC_LOGIN_PUBLIC):
0xffff0005 (error origin 0x3)
TA_FLAG_EXEC_DDR is deprecated but it is necessary to be executed with
optee_os <= 3.0.0.

acipher: fix TA_FLAGS to be compatible with old version of optee_os

---

README.md

github: update the link to optee_examples documentation

---

hotp/ta/hotp_ta.c

The size for the key to register, provided by non-secure world is never
checked, hence it's possible to do an buffer overflow attack in the
HOTP TA. Add a check to control that the size provided isn't greater
that sizeof(K) fixes the issue.
Reported-by: Ronan Loftus <loftus@riscure.com>

hotp: fix buffer overflow issue

---

random/ta/random_example_ta.c

TEE_GenerateRandom() has the [out] annotation which mandates that the
buffer "SHALL not reside in a block of shared memory owned by a client
of the Trusted Application" [1]. Fix this by allocating a temporary
buffer from the heap.
[1] TEE Internal Core API Specification v1.1
Signed-off-by: Jerome Forissier <jerome@forissier.org>

random: use private buffer

---

acipher/host/main.c
aes/host/main.c
hello_world/host/main.c
random/host/main.c

Signed-off-by: Aleksandr Anisimov <a.anisimov@omprussia.ru>

fix typo in comments for acipher, aes, hello_world and random examples

---

.gitignore
plugins/Android.mk
plugins/CMakeLists.txt
plugins/Makefile
plugins/host/Makefile
plugins/host/main.c
plugins/syslog/CMakeLists.txt
plugins/syslog/Makefile
plugins/syslog/syslog_plugin.c
plugins/ta/Android.mk
plugins/ta/Makefile
plugins/ta/include/plugin_ta.h
plugins/ta/plugin_ta.c
plugins/ta/sub.mk
plugins/ta/user_ta_header_defines.h

TEE clients can add to the tee-supplicant an own plugin.
This feature makes the supplicant a bit more flexible
in terms of providing services. Any external TEE services
can be designed as a tee-supplicant plugin.
User TAs and also the OP-TEE kernel code can interact
with the plugins with the help of the special PRC.
This patch adds example of using the plugin framework.
By default in tee-supplicant there is 'syslog' plugin.
It can write log messages from OP-TEE (TAs or kernel)
to system log. You can find the implementation of the plugin
in 'tee-supplicant/plugins/syslog/syslog_plugin.c' file.
This example adds a new TA, which interacts with
'syslog' plugin with the help of the plugin-pta.
This TA increments a value and prints some strings
to the syslog. Also patch adds a host CA, which …

plugins: example of using supplicant syslog plugin from TA code

---

acipher/host/Makefile
aes/host/Makefile
hello_world/host/Makefile
hotp/host/Makefile
random/host/Makefile
secure_storage/host/Makefile

Distributions bring their own sets of LDFLAGS, and some fail when
binaries do not match their expectation after ignoring those flags.
Eg. for yocto:
ERROR: optee-examples-3.12.0+gitAUTOINC+9a755dcf4d-r0 do_package_qa: QA Issue: File /usr/bin/optee_example_secure_storage in package optee-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/optee_example_acipher in package optee-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)
...
Signed-off-by: Yann Dirson <yann@blade-group.com>

Use LDFLAGS for host binaries

---

Makefile

"exit -1" has traditionally had "exit 255" result, but starts to be
rejected by some shells (eg. dash, which is is the default on many
Debian systems):
host$ bash
$ exit -1
exit
host$ echo $?
255
host$ dash
$ exit -1
dash: 1: exit: Illegal number: -1
$
host$ echo $?
2
Signed-off-by: Yann Dirson <yann@blade-group.com>

Makefile: shell fixes

---

Makefile

Comparison with "==" is non-portable, resulting in an error:
/bin/sh: 6: [: acipher: unexpected operator
/bin/sh: 6: [: plugins: unexpected operator
/bin/sh: 6: [: hello_world: unexpected operator
/bin/sh: 6: [: hotp: unexpected operator
/bin/sh: 6: [: aes: unexpected operator
/bin/sh: 6: [: random: unexpected operator
/bin/sh: 6: [: secure_storage: unexpected operator
if /bin/sh doesnt point to bash.
Signed-off-by: Alejandro Enedino Hernandez Samaniego <alhe@linux.microsoft.com>
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

Makefile: Fix non-portable sh check for plugins

---

plugins/syslog/syslog_plugin.c

There is a over-print in current version of `syslog_plugin.c`, since `(const char*) data` is not NULL terminated.
```
Work logic: REE --> plugin TA --> syslog plugin in REE --> syslog
See the log from TEE through 'journalctl'
Attempt #1: TEEC_InvokeCommand() success; res=0 orig=0x4
Attempt #2: TEEC_InvokeCommand() success; res=0 orig=0x4
Attempt #3: TEEC_InvokeCommand() success; res=0 orig=0x4
Attempt #4: TEEC_InvokeCommand() success; res=0 orig=0x4
Attempt #5: TEEC_InvokeCommand() success; res=0 orig=0x4
Apr 29 00:53:16 buildroot daemon.info tee-supplicant[137]: Hello, plugin! value = 0x0^RX_^H~^B
Apr 29 00:53:18 buildroot daemon.info tee-supplicant[137]: Hello, plugin! value = 0x1
Apr 29 00:53:20 buildroot daemon.info tee-supplicant[137]: Hello, plugin! value = 0x2y0^Y7m^U^A
Apr 29 …
```

plugins: fix formatting string of the syslog()

---

plugins/syslog/CMakeLists.txt

Adds missing dependency of plugins/syslog example on libteec header files that are brought in by libteec. The issue was reported by compiler with the below build error message:
/tmp/optee/optee_examples/plugins/syslog/syslog_plugin.c:8:10: fatal error: tee_plugin_method.h: No such file or directory
8 | #include <tee_plugin_method.h>
|          ^~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

pluging: add missing of dependency syslog on teec

---

hotp/host/main.c
hotp/ta/hotp_ta.c

Resolve the issue of global variables in TA, which currently do not have 
isolation when accessed by multiple CAs. It is suggested to attach the 
variables to session_ctx for easy access when needed.
Signed-off-by: Shiqi Liu [erha_email@163.com](mailto:erha_email@163.com)

hotp: use sess_ctx instead of global variables

---

acipher/ta/user_ta_header_defines.h
aes/ta/user_ta_header_defines.h
secure_storage/ta/user_ta_header_defines.h

Remove misleading TA properties in new added examples

---

aes/ta/aes_ta.c

Call TEE_Free on key pointer after the key is copied into the object.
Fixes: #121

aes: fix key memory leak

---

CMakeLists.txt

CMake 4.0 was released [1] which dropped compatibility with versions older than 3.5 and causes cmake_minimum_required(3.4) to fail. Bump the minimum required version to 3.5, which was released 9 years ago.
[1] https://www.kitware.com/cmake-4-0-0-available-for-download/
With v4.0.0 the following build error is observed:
|  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|  Compatibility with CMake < 3.5 has been removed from CMake.
|
|  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|  to tell CMake that the project requires at least <min> but has been updated
|  to work with policies introduced by <max> or earlier.
|
|  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.

cmake: raise minimum required to 3.5

---

.github/workflows/stales.yml

Update actions/stale@v4.1.0 to the latest version (v10.0.0). One difference is that issues and PRs are closed by the bot as "not_planned" rather than "completed", which is the main reason for updating.

github: update stale workflow to v10.0.0
